// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9wWQhiPwZJ7L6ggOtpDxdS92jklQbPjc',
    appId: '1:174614489763:web:e1ac307bdba3da7e90ad16',
    messagingSenderId: '174614489763',
    projectId: 'geniozinho-adf35',
    authDomain: 'geniozinho-adf35.firebaseapp.com',
    storageBucket: 'geniozinho-adf35.firebasestorage.app',
    measurementId: 'G-WE303YPQX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcDInqNK6jffaez8my0c1V3p7CRuBWTk8',
    appId: '1:174614489763:android:aeb817139767a0f990ad16',
    messagingSenderId: '174614489763',
    projectId: 'geniozinho-adf35',
    storageBucket: 'geniozinho-adf35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYz_XImzv8g5dNQzApwj77cUxOfq38pA4',
    appId: '1:174614489763:ios:4cfa81c492a911a290ad16',
    messagingSenderId: '174614489763',
    projectId: 'geniozinho-adf35',
    storageBucket: 'geniozinho-adf35.firebasestorage.app',
    iosBundleId: 'br.com.digitoinovacao.geniozinho',
  );
}
